name: Build Test and Deploy

on: 
   push:
      branches:
        - main
   pull_request:
      branches:
        - main

env:
   PROJECT_VERSION: 1.0.0

jobs:
   build:
      name: Build and Cache Dependencies
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v4.2.2
         - name: Setup Java JDK
           uses: actions/setup-java@v4.5.0
           with:
              java-version: 17
              distribution: temurin

         -  name: Cache
            uses: actions/cache@v4.1.2
            with:
               path: ${{ github.workspace }}/.m2/repository
               key : ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml')}}

         - name: Build Project with Maven
           run: mvn clean pakage -DskipTests
           env:
              MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository"
